# Generated by Django 5.1.6 on 2025-04-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_orders', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Sales Data',
                'ordering': ['-date'],
            },
        ),
    ]
